### ISSUE TITLE
problem foreman 2.1.4

### ISSUE THREAD

**Issue by stephenbcollier** [grizzthedj/smart_proxy_ipam#48]
After installing as I did on version 1.24 I'm getting this in the smart proxy logs

Disabling all modules in the group ['externalipam'] due to a failure in one of them: (<unknown>): mapping values are not allowed in this context at line 2 column 9 

I assume foreman 2.1.4 has the smart proxy code built in. Is there a particular version of the gems required?

**Comment by grizzthedj** [comment]
@stephenbcollier For Foreman version 2.1.4, you need to use `smart_proxy_ipam` version 0.0.22. The latest version of the plugin only works with Foreman version 2.3 or greater. More info [here](https://community.theforeman.org/t/dns-dhcp-ipam-software-that-plays-nicely-with-foreman/20974/4)

**Comment by stephenbcollier** [comment]
Thanks
