### ISSUE TITLE
request: adding hostname with fqdn to add_ip_to_subnet

### ISSUE THREAD

**Issue by PawS60** [grizzthedj/smart_proxy_ipam#55]
phpipam use field hostname in api address controler.

**Comment by grizzthedj** [comment]
Sorry for the late reply, but I don't understand your request. Could you clarify and/or add more details?

**Comment by pawelskrzypekwp** [comment]
when you post to /api/my_app/addresses/first_free/ put fqdn in parametr hostname

**Comment by PawS60** [comment]
in phpipam plugin, function add_ip_to_subnet put in data parameter hostname filled with fqdn
here:
def add_ip_to_subnet(ip, params)
data = { subnetId: params[:subnet_id], ip: ip, description: 'Address auto added by Foreman' }
subnet = @api_resource.post('addresses/', data.to_json)
json_body = JSON.parse(subnet.body)
return nil if json_body['code'] == 201
{ error: 'Unable to add IP to External IPAM' }
end
